### ISSUE TITLE
newest visual studio seems doesn't support this project?

### ISSUE THREAD

**Issue by ZhaoTY2077** [biobibibi/MultiMSIProcessor#2]
Dear developer of MMP:

Thanks for your development of MMP software! 

I'm not an experienced Visual Studio user, so there's some problems hard for me to address. 

I tried to run MMP project following the users guide. After downloaded visual studio and the whole project from github, I tried to open the "./MultiMSIProcessor-master/MultiMSIProcessor.sln" as you said, however, VS reminded me that i have to install some additional components follow the "solution". and the MMP is not imported succesfully. but when I click the "install" button, nothing happens, 

Besides, I have also tried to clone the project repository through the github link in users guide, but it also failed with the same feedback. 

I would wondering how can i fix this problem. It would be appreciated if you can help me with that. 
![1723802258241](https://github.com/user-attachments/assets/7fe193f5-9830-4575-bbdb-6e8a3c6ca68f)
![1723802663505](https://github.com/user-attachments/assets/f830faa4-fb19-46e1-9dc9-0cab2e7b6ad2)

best, Troy

**Comment by biobibibi** [comment]
Hi Troy:

Thank you for choosing MMP and letting us know.

I am wondering if you completed the third step in the Prerequisite of the user's manual: "In the Solution Explorer of the Visual Studio, right-click the Project, and find the Add-Project Reference", since the problem looks like resulting from components missing.

Looking forward to your reply.

Siwei

**Comment by ZhaoTY2077** [comment]
Hi Siwei:

Thanks a lot for your reply!

I think the problem I asked totally results from my unfamiliarity with visual studio. I found out that I just need to install some necessary components for this project to let me to move on. 

But for the fourth step of the guide, I can't find the **Supplementary_dll folder** located in **"./MultiMSIProcessor-master/Supplementary files/dlls/" folder** as you mentioned. Since there are a bunch of .dll files in that folder, and it seems the visual studio would only allow to add **files** instead of **a folder** for this step. 
![1724030359511](https://github.com/user-attachments/assets/6f560970-2dc6-475c-844b-a9c023d9813b)
and if I just pick either one of the .dll files to add, it would remind me the reference is invalid or not supported. 
![1724030663495](https://github.com/user-attachments/assets/2a261fbb-f45c-4691-b7f6-e55d44f48d71)

What should I do to successfully add the **Supplementary_dll folder** you mentioned in the fourth step? 

Looking forward to your reply

Best, Troy

**Comment by biobibibi** [comment]
Hi Troy, 

Sorry for the confusion about the folder or DLL files. I have updated the user guide.

You can use ctrl+A to select all the DLLs and add them all collectively.

For the main question, it looks like a commonly asked question as brought up in 
https://learn.microsoft.com/en-us/answers/questions/1341393/visual-studio-2022-c-project-references
and
https://developercommunity.visualstudio.com/t/visual-studio-2019-1602-the-reference-is-invalid-o/538956.
I think you can select all the DLLs in the current project and right-click, choose delete to clear all the DLLs, as shown here:

![1724108064051](https://github.com/user-attachments/assets/0f39219c-4d60-44b5-8ac5-4910125d009d)

After this, add all the DLLs in the "./MultiMSIProcessor-master/Supplementary files/dlls/".

I hope this resolves the issue. Feel free to reach out with any further questions

Thanks.

Siwei

**Comment by ZhaoTY2077** [comment]
Hi Siwei:
Thanks for your reply again
I have solved the previous problem following your guide, remove, then add all .dll files as references again, then Ctrl+B...
however, it results in: 
![1724123956812](https://github.com/user-attachments/assets/c29d8b5e-901a-496e-ba2a-b50ec145f3b8)
as the figure shows, one of the files named Form1.resx is unable to be handled. i'm not sure how to solve this. 

Best, Troy

**Comment by biobibibi** [comment]
Hi Troy,

Regarding "https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3821?view=vs-2022", you can try to do the following:

1. Close MMP and visual studio;
2. find this Form1.resx with File Explorer, which should be located in the ".../[MultiMSIProcessor/MultiMSIProcessor/[Form1.resx]";
3. right click and select the Properties;
4. check the 'unblock' option and click on apply;
5. Open MMP again and try to build it.

I also find one screenshot online from "https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o":
![image](https://github.com/user-attachments/assets/f0a8aede-5b5e-44b2-b842-aaefbc950425)

I hope this will work.

Kind regards

Siwei

**Comment by ZhaoTY2077** [comment]
It works! 
Really appreciated for all of your patient replies, I have to apologize that I didn't managed to find those already existed solutions by myself. Now I learned how and where to looking for the solutions for those problems. 

Thank you so much siwei!

Best, Troy

**Comment by biobibibi** [comment]
Hi Troy

Glad to hear that! There is no need to apologize, we all learned a lot. 

And I'm closing this issue now. Please feel free to bring up any additional problems related to utilizing MMP for further discussion.   

Kind regards

Siwei
